# These are supported funding model platforms / پلتفرم‌های حمایت مالی پشتیبانی‌شده
#
# eOVPN-Pro is developed with love and is free forever. If you would like to
# support the project, please use the direct donation link below.
# eOVPN-Pro با عشق توسعه می‌یابد و همیشه رایگان می‌ماند؛ برای حمایت مالی از
# لینک مستقیم زیر استفاده کنید.

custom: ["https://www.MahdiArts.ir/donate"]
