"""
eOVPN-Pro OpenVPN 3 Enumeration Generator
تولیدکننده ثابت‌های شمارشی OpenVPN 3 در eOVPN-Pro

Generates ``enums.h`` (C macros) from the Python ``openvpn3`` bindings so the
native C layer can compare OpenVPN 3 status codes.
این اسکریپت فایل ``enums.h`` (ماکروهای C) را از بایندینگ پایتون ``openvpn3``
تولید می‌کند تا لایه بومی C بتواند کدهای وضعیت OpenVPN 3 را مقایسه کند.
"""

import sys

# The python3-openvpn3 package must be importable at build time.
# پکیج python3-openvpn3 باید هنگام ساخت قابل ایمپورت باشد.
try:
    from openvpn3.constants import StatusMajor, StatusMinor
except ImportError:
    print(
        "extract_enums.py: cannot import 'openvpn3.constants'. "
        "Install the python3-openvpn3 package (e.g. 'pip install openvpn3') "
        "or build with -Dopenvpn3=false to disable the OpenVPN 3 backend.",
        file=sys.stderr,
    )
    sys.exit(1)

ENUMS_HEADER = "enums.h"


def write_enum_definitions() -> None:
    """Writes the enum macros to enums.h (truncating any stale content)."""
    # 'w' mode guarantees a clean file on every run (no duplicate #defines)
    # حالت نوشتن از ابتدا تضمین می‌کند فایل در هر اجرا تمیز باشد (بدون تعریف تکراری)
    with open(ENUMS_HEADER, "w", encoding="utf-8") as f:
        f.write("/* Generated by extract_enums.py - DO NOT EDIT */\n")
        for k, v in StatusMajor.__members__.items():
            f.write(f"#define MAJOR_{k} {v.value}\n")
        for k, v in StatusMinor.__members__.items():
            f.write(f"#define MINOR_{k} {v.value}\n")
    print(f"extract_enums.py: wrote {ENUMS_HEADER}")


if __name__ == "__main__":
    write_enum_definitions()
