int get_specific_connection_status (char *session_path);
char *get_version (void);
char *import_config (char *name, char *config_str);
char *prepare_tunnel (char *config_object);
void init_unique_session (char *session_object);
int set_dco (char *session_object, int set_to);
char *is_ready_to_connect (void);
int send_auth (char *session_object, int type, int group, int id, char *value);
int connect_vpn (void);
int disconnect_vpn (void);
int pause_vpn (char *reason);
int resume_vpn (void);
char *p_get_version (void);
void eovpn_free (char *value);
